// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4oCdEJenl6ai3ubasvaihNr9w2nr3JcM',
    appId: '1:163513503884:web:399cf34937be05bb2e6ba9',
    messagingSenderId: '163513503884',
    projectId: 'workersinn-945d4',
    authDomain: 'workersinn-945d4.firebaseapp.com',
    storageBucket: 'workersinn-945d4.appspot.com',
    measurementId: 'G-1FEZR4FRFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVW6R446fiq2lVnmQh7pYnnmx_vyAmb40',
    appId: '1:163513503884:android:b2b23a339eb75e022e6ba9',
    messagingSenderId: '163513503884',
    projectId: 'workersinn-945d4',
    storageBucket: 'workersinn-945d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw9noBkz-piEuioOR48sSomh9aPuUkXp4',
    appId: '1:163513503884:ios:11a466cd300fc5ce2e6ba9',
    messagingSenderId: '163513503884',
    projectId: 'workersinn-945d4',
    storageBucket: 'workersinn-945d4.appspot.com',
    iosClientId: '163513503884-dqmhk2crk1qk3iapa2p244ln7tnm4c2v.apps.googleusercontent.com',
    iosBundleId: 'com.example.workersInn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw9noBkz-piEuioOR48sSomh9aPuUkXp4',
    appId: '1:163513503884:ios:11a466cd300fc5ce2e6ba9',
    messagingSenderId: '163513503884',
    projectId: 'workersinn-945d4',
    storageBucket: 'workersinn-945d4.appspot.com',
    iosClientId: '163513503884-dqmhk2crk1qk3iapa2p244ln7tnm4c2v.apps.googleusercontent.com',
    iosBundleId: 'com.example.workersInn',
  );
}
